### ISSUE TITLE
Supporting Markdown inside Gherkin

### ISSUE THREAD

**Issue by jimlloyd** [bmabey/gherkin-pygments-lexer#3]
I'd like to be able to use Markdown inside Gherkin. We currently use [groc](https://github.com/nevir/groc) which supports both Markdown and Gherkin via pygments, but as far as I can tell there currently isn't a way for pygments to recognize Markdown within a .feature file. I've only spent 15 minute so far looking a pygments lexer documentation, but it seems that this lexer is the one that would need to be extended.

Is this a feature you can easily add? Or if you'd prefer to give me some tips, I may be able to produce a PR.

**Comment by bmabey** [comment]
I'm no longer maintaining this project.. please see https://github.com/cucumber/gherkin-pygments-lexer
